# This is used by Dockerfile.release to serve the built Vue app with nginx in production.
# Nginx configuration for the React frontend 
# Needed because nginx serves static files and doesn't know about React Router.
# Without this, refreshing or directly accessing a route like /tasks would 404.

server {
    listen 80;

    location /api/ {
        proxy_pass http://backend:8000/;
    }
    
    location /media/ {
        proxy_pass http://backend:8000/media/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}